version: '3.8'

volumes:
  hlab-datastore:

services:
  certogo-database:
    container_name: hlab-database
    image: postgres:15-alpine3.16
    restart: on-failure
    volumes:
      - hlab-datastore:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hlab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    command: postgres -c 'max_connections=400'
    ports:
      - '5433:5432'
